### ISSUE TITLE
Final Report Format

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/Workflows_Group_306#41]
Always render a .pdf of .md version of your report so it can be read in Github.

**Comment by TBarasch** [comment]
Had some issues originally with .md so did HTML for the second milestone.
Fixed and now using .md as requested.

**Comment by TBarasch** [comment]
For the record though, when asked Firas said any of the outputs would be fine:
https://ubc-mds.slack.com/archives/C24HUNRJL/p1580589420201100
