### ISSUE TITLE
Is ELO really THAT bad?

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/Workflows_Group_306#51]
> We find that both models achieve similar results, with 0.771% accuracy
> 
> for the logistic regression and 0.767% accuracy for the random forest
> 
> classifier. Which overall is a pretty unreliable prediction model, casting doubt over the method presented by FiveThirtyEight.

0.8% ? That is pretty low... are you sure there isn't a typo in your report ?

**Comment by TBarasch** [comment]
Silly error by me when writing up the repot, it is 80% which is 0.8, corrected for milestone 4.
