### ISSUE TITLE
Visualizations Feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/Workflows_Group_306#52]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [x] Great job adding figure numbers and captions! Though your captions could have been a bit more informative, overall this is a very good practice. Also, both figures are called Figure 1
- - [ ] Figure 1
	- - [ ] This is a really effective plot, great job!
	- - [ ] I would make the plot a bit smaller, and the textsize a bit bigger so it's proportionate to the rest of your report
- - [ ] Figure 2
	- - [ ] consider combining Figure 1 and 2 together in a side-by-side way and call them A, B so it's easier to interpret, read, and takes up less space
- - [ ] I think your figures are very reasonable for your project and research question. Nice work!

**Comment by TBarasch** [comment]
fixed figure title, did not adjust size of figure generated directly from the scikit learn package, time constraints.
